// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/create": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/webhooks/checkouts": {
    params: {};
  };
  "/track/unsubscribe": {
    params: {};
  };
  "/push-unsubscribe": {
    params: {};
  };
  "/webhooks/orders": {
    params: {};
  };
  "/push-subscribe": {
    params: {};
  };
  "/track/confirm": {
    params: {};
  };
  "/popup-config": {
    params: {};
  };
  "/popup-signup": {
    params: {};
  };
  "/track/click": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/push-sw": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/preview/email": {
    params: {};
  };
  "/app/flows": {
    params: {};
  };
  "/app/playbook/:id": {
    params: {
      "id": string;
    };
  };
  "/app/additional": {
    params: {};
  };
  "/app/onboarding": {
    params: {};
  };
  "/app/flows/:id": {
    params: {
      "id": string;
    };
  };
  "/app/playbooks": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/journey": {
    params: {};
  };
  "/app/popup": {
    params: {};
  };
  "/app/push": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/create" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/shop/redact" | "/webhooks/checkouts" | "/track/unsubscribe" | "/push-unsubscribe" | "/webhooks/orders" | "/push-subscribe" | "/track/confirm" | "/popup-config" | "/popup-signup" | "/track/click" | "/auth/login" | "/push-sw" | "/auth/*" | "/app" | "/app/preview/email" | "/app/flows" | "/app/playbook/:id" | "/app/additional" | "/app/onboarding" | "/app/flows/:id" | "/app/playbooks" | "/app/settings" | "/app/journey" | "/app/popup" | "/app/push";
  };
  "routes/webhooks.customers.data_request.jsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.jsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.create.jsx": {
    id: "routes/webhooks.customers.create";
    page: "/webhooks/customers/create";
  };
  "routes/webhooks.customers.redact.jsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.jsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.shop.redact.jsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/webhooks.checkouts.jsx": {
    id: "routes/webhooks.checkouts";
    page: "/webhooks/checkouts";
  };
  "routes/track.unsubscribe.jsx": {
    id: "routes/track.unsubscribe";
    page: "/track/unsubscribe";
  };
  "routes/push-unsubscribe.jsx": {
    id: "routes/push-unsubscribe";
    page: "/push-unsubscribe";
  };
  "routes/webhooks.orders.jsx": {
    id: "routes/webhooks.orders";
    page: "/webhooks/orders";
  };
  "routes/push-subscribe.jsx": {
    id: "routes/push-subscribe";
    page: "/push-subscribe";
  };
  "routes/track.confirm.jsx": {
    id: "routes/track.confirm";
    page: "/track/confirm";
  };
  "routes/popup-config.jsx": {
    id: "routes/popup-config";
    page: "/popup-config";
  };
  "routes/popup-signup.jsx": {
    id: "routes/popup-signup";
    page: "/popup-signup";
  };
  "routes/track.click.jsx": {
    id: "routes/track.click";
    page: "/track/click";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/push-sw.jsx": {
    id: "routes/push-sw";
    page: "/push-sw";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/preview/email" | "/app/flows" | "/app/playbook/:id" | "/app/additional" | "/app/onboarding" | "/app/flows/:id" | "/app/playbooks" | "/app/settings" | "/app/journey" | "/app/popup" | "/app/push";
  };
  "routes/app.preview.email.jsx": {
    id: "routes/app.preview.email";
    page: "/app/preview/email";
  };
  "routes/app.flows._index.jsx": {
    id: "routes/app.flows._index";
    page: "/app/flows";
  };
  "routes/app.playbook.$id.jsx": {
    id: "routes/app.playbook.$id";
    page: "/app/playbook/:id";
  };
  "routes/app.additional.jsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.onboarding.jsx": {
    id: "routes/app.onboarding";
    page: "/app/onboarding";
  };
  "routes/app.flows.$id.jsx": {
    id: "routes/app.flows.$id";
    page: "/app/flows/:id";
  };
  "routes/app.playbooks.jsx": {
    id: "routes/app.playbooks";
    page: "/app/playbooks";
  };
  "routes/app.settings.jsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.journey.jsx": {
    id: "routes/app.journey";
    page: "/app/journey";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.popup.jsx": {
    id: "routes/app.popup";
    page: "/app/popup";
  };
  "routes/app.push.jsx": {
    id: "routes/app.push";
    page: "/app/push";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.jsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.jsx");
  "routes/webhooks.customers.create": typeof import("./app/routes/webhooks.customers.create.jsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.jsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.jsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.jsx");
  "routes/webhooks.checkouts": typeof import("./app/routes/webhooks.checkouts.jsx");
  "routes/track.unsubscribe": typeof import("./app/routes/track.unsubscribe.jsx");
  "routes/push-unsubscribe": typeof import("./app/routes/push-unsubscribe.jsx");
  "routes/webhooks.orders": typeof import("./app/routes/webhooks.orders.jsx");
  "routes/push-subscribe": typeof import("./app/routes/push-subscribe.jsx");
  "routes/track.confirm": typeof import("./app/routes/track.confirm.jsx");
  "routes/popup-config": typeof import("./app/routes/popup-config.jsx");
  "routes/popup-signup": typeof import("./app/routes/popup-signup.jsx");
  "routes/track.click": typeof import("./app/routes/track.click.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/push-sw": typeof import("./app/routes/push-sw.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.preview.email": typeof import("./app/routes/app.preview.email.jsx");
  "routes/app.flows._index": typeof import("./app/routes/app.flows._index.jsx");
  "routes/app.playbook.$id": typeof import("./app/routes/app.playbook.$id.jsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.jsx");
  "routes/app.onboarding": typeof import("./app/routes/app.onboarding.jsx");
  "routes/app.flows.$id": typeof import("./app/routes/app.flows.$id.jsx");
  "routes/app.playbooks": typeof import("./app/routes/app.playbooks.jsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.jsx");
  "routes/app.journey": typeof import("./app/routes/app.journey.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
  "routes/app.popup": typeof import("./app/routes/app.popup.jsx");
  "routes/app.push": typeof import("./app/routes/app.push.jsx");
};